import Foundation

/// The spike's fixtures, generated at run time and never written to the repository.
///
/// §11 is the reason this file exists at all: the 5 MB buffer and the diff pair have to come
/// from somewhere, and "somewhere" must not be an engine transcript, a real path on this
/// machine or an author's identifier. A seeded generator is the only source with none of those
/// properties, and being seeded it also makes two runs of the harness comparable.
enum Fixtures {

    /// A 64-bit linear congruential generator. Not a good random source and not meant to be —
    /// it is meant to produce the same bytes on every machine, for ever.
    struct Deterministic {
        private var state: UInt64
        init(seed: UInt64) { state = seed }
        mutating func next() -> UInt64 {
            state = state &* 6_364_136_223_846_793_005 &+ 1_442_695_040_888_963_407
            return state
        }
        mutating func int(_ bound: Int) -> Int { Int(next() >> 11) % max(bound, 1) }
        mutating func pick<T>(_ items: [T]) -> T { items[int(items.count)] }
    }

    private static let nouns = ["buffer", "channel", "cursor", "descriptor", "envelope", "frame",
                                "handle", "index", "journal", "ledger", "marker", "node",
                                "offset", "packet", "quota", "record", "segment", "token"]
    private static let verbs = ["append", "collect", "drain", "encode", "flush", "gather",
                                "inspect", "merge", "normalise", "prune", "resolve", "seal"]
    private static let types = ["Int", "String", "Double", "Bool", "Data", "UInt64", "[String]"]

    /// A synthetic Swift source file of at least `byteCount` UTF-8 bytes.
    ///
    /// Swift rather than plain text because the language matters twice over: the buffer has to
    /// be tokenised by a real Monarch grammar for the frame-time histogram to mean anything, and
    /// that grammar arrives as a lazy chunk, which is the third load path S3 measures.
    static func swiftSource(ofAtLeast byteCount: Int) -> String {
        var rng = Deterministic(seed: 0x5133_A17E_51_5EED)
        var blocks: [String] = ["// Synthetic fixture generated by the C7.2 S3 harness. Not real source.\nimport Foundation\n\n"]

        // The running total is kept per block rather than asked of the accumulated string:
        // `utf8.count` is O(n) on a Swift String, so calling it once per loop over a 5 MB result
        // is quadratic — a generator that takes minutes instead of milliseconds. This was found
        // by running it, not by reading it.
        var written = blocks[0].utf8.count
        var index = 0

        while written < byteCount {
            let name = "\(rng.pick(nouns).capitalized)\(index)"
            var block = "/// A generated type, \(index), holding \(rng.pick(nouns)) state.\n"
            block += "struct \(name): Sendable, Hashable {\n"
            let fieldCount = 3 + rng.int(5)
            for field in 0..<fieldCount {
                block += "    var \(rng.pick(nouns))\(field): \(rng.pick(types))\n"
            }
            let methodCount = 2 + rng.int(4)
            for method in 0..<methodCount {
                let verb = rng.pick(verbs)
                block += "\n    func \(verb)\(method)(_ value: Int) -> Int {\n"
                block += "        guard value > \(rng.int(1000)) else { return \(rng.int(97)) }\n"
                block += "        var total = value &* \(1 + rng.int(31))\n"
                block += "        for step in 0..<\(2 + rng.int(9)) {\n"
                block += "            total = total &+ step &* \(1 + rng.int(17))\n"
                block += "        }\n"
                block += "        return total % \(101 + rng.int(9899))\n"
                block += "    }\n"
            }
            block += "}\n\n"
            written += block.utf8.count
            blocks.append(block)
            index += 1
        }
        return blocks.joined()
    }

    /// A 2,000-line pair differing in roughly a fifth of its lines: insertions, deletions and
    /// modifications, spread rather than clustered, so the diff editor has real work and the
    /// change count is a number a human can sanity-check.
    static func diffPair(lines: Int) -> (original: String, modified: String, expectedChangedRegions: Int) {
        var rng = Deterministic(seed: 0xD1FF_0000_5EED_2000)
        var original: [String] = []
        var modified: [String] = []
        var regions = 0

        for line in 0..<lines {
            let text = "    let \(rng.pick(nouns))\(line) = \(verbFor(&rng))(\(rng.int(10_000)))"
            switch rng.int(10) {
            case 0:
                original.append(text)
                modified.append(text.replacingOccurrences(of: "let", with: "var") + " // changed")
                regions += 1
            case 1:
                original.append(text)
                regions += 1
            case 2:
                original.append(text)
                modified.append(text)
                modified.append("    // inserted at \(line)")
                regions += 1
            default:
                original.append(text)
                modified.append(text)
            }
        }
        return (original.joined(separator: "\n"), modified.joined(separator: "\n"), regions)
    }

    private static func verbFor(_ rng: inout Deterministic) -> String { rng.pick(verbs) }
}
