#!/usr/bin/env bash
#
# Builds the committed Monaco bundle for `EditorCore` (child spec
# docs/doperpowers/specs/2026-09-07-c7.2-editor-core.md, Design §1 and §2).
#
# One document entry and five worker entries, built with `bun build` from the Monaco release
# pinned in Tools/monaco/package.json and Tools/monaco/bun.lock. Code splitting stays on: the
# ~85 basic-language grammars are behind lazy `import()`s and splitting is what keeps them off
# the cold-load path, so the output is a directory of ~100 files rather than a handful.
#
# The output directory is replaced *whole*. A file left behind by a previous Monaco version
# would otherwise survive silently in the committed bundle, which is exactly the failure a
# generated-and-committed artefact invites.
#
# Nothing under Tools/monaco/.work/ is committed: it holds node_modules, the entry stubs and
# bun's raw output. Committed are Tools/monaco/package.json, Tools/monaco/bun.lock, and the
# bundle itself with its generated VERSION, its generated stylesheet manifest (styles.json and
# styles.css) and Monaco's MIT licence.
#
# Usage: Tools/build-monaco.sh   (from anywhere; paths are derived from this script's location)

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
monaco_dir="$repo_root/Tools/monaco"
work_dir="$monaco_dir/.work"
out_dir="$work_dir/out"
src_dir="$work_dir/src"
resource_dir="$repo_root/Workbench/Sources/EditorCore/Resources/monaco"

if ! command -v bun >/dev/null 2>&1; then
    cat >&2 <<'MISSING'
build-monaco.sh: `bun` is not on PATH.

The Monaco bundle is built with bun and cannot be built without it. Install it with

    curl -fsSL https://bun.sh/install | bash

then re-run Tools/build-monaco.sh. Nothing else is missing: the Monaco version is pinned in
Tools/monaco/package.json and Tools/monaco/bun.lock, and the build needs no other tool.

The committed bundle under Workbench/Sources/EditorCore/Resources/monaco is unchanged; a
checkout that does not rebuild it does not need bun at all.
MISSING
    exit 1
fi

# Recorded into VERSION, not enforced. The lockfile pins Monaco's dependency graph; it does not
# pin the executable that reads it, and this script produces minified, content-hashed output with
# whichever bun is installed — so the committed inputs alone do not determine the committed bytes.
# Tracker entry 106 holds the closer.
bun_version="$(bun --version)"

# --- install --------------------------------------------------------------------------------
# The install runs in the ignored working directory, from the committed manifest and lockfile,
# so the resolved tree is the one the lockfile pins and never whatever npm serves today.

mkdir -p "$work_dir"
cp "$monaco_dir/package.json" "$work_dir/package.json"
cp "$monaco_dir/bun.lock" "$work_dir/bun.lock"
(cd "$work_dir" && bun install --frozen-lockfile)

monaco_package="$work_dir/node_modules/monaco-editor"
monaco_version="$(cd "$work_dir" && bun --print 'require("./node_modules/monaco-editor/package.json").version')"

# --- entry stubs ----------------------------------------------------------------------------
# `editor.main.js` in 0.56.0 already is contract W4's contents: all ~85 basic languages (lazily),
# the css/html/json/typescript language features, and every editor and diff-editor contribution.
# The tree-shaking therefore follows from the entry point rather than from a hand-curated import
# list that would drift at every Monaco bump.

rm -rf "$src_dir" "$out_dir"
mkdir -p "$src_dir"

cat > "$src_dir/editor.js" <<'ENTRY'
// The document entry. Generated by Tools/build-monaco.sh; edit the script, not this file.
import * as monaco from "monaco-editor/editor/editor.main.js";

// The bootstrap (Resources/bootstrap, this leaf's own source) reaches the API through the
// global, so it does not have to know the bundle's module graph.
globalThis.monaco = monaco;

export * from "monaco-editor/editor/editor.main.js";
ENTRY

# The five workers. Each is a side-effect entry: it installs its own message handler and
# exports nothing. Monaco 0.56.0's `exports` map is `"./*.js": "./esm/vs/*.js"`, which is why
# the specifiers are spelled this way and not `monaco-editor/esm/vs/…`.
write_worker_entry() {
    printf '// Generated by Tools/build-monaco.sh.\nimport "%s";\n' "$2" > "$src_dir/$1"
}
write_worker_entry editor.worker.js "monaco-editor/editor/editor.worker.js"
write_worker_entry ts.worker.js "monaco-editor/language/typescript/ts.worker.js"
write_worker_entry json.worker.js "monaco-editor/language/json/json.worker.js"
write_worker_entry css.worker.js "monaco-editor/language/css/css.worker.js"
write_worker_entry html.worker.js "monaco-editor/language/html/html.worker.js"

# --- build ----------------------------------------------------------------------------------

(cd "$work_dir" && bun build \
    "src/editor.js" \
    "src/editor.worker.js" \
    "src/ts.worker.js" \
    "src/json.worker.js" \
    "src/css.worker.js" \
    "src/html.worker.js" \
    --outdir=out \
    --splitting \
    --format=esm \
    --minify \
    --target=browser)

# --- publish ---------------------------------------------------------------------------------
# Replaced whole, then stamped. The stamp carries no build date on purpose: rebuilding an
# unchanged input must leave `git status` clean, and a date makes every rebuild a diff.

rm -rf "$resource_dir"
mkdir -p "$resource_dir"
cp -R "$out_dir"/. "$resource_dir"/
cp "$monaco_package/LICENSE" "$resource_dir/LICENSE"

cat > "$resource_dir/VERSION" <<STAMP
# Generated by Tools/build-monaco.sh. Do not edit; re-run the script.
# No build date: a rebuild of unchanged inputs is a no-op, so git stays clean.
monaco-editor $monaco_version
bun $bun_version
STAMP

# --- stylesheet manifest and loader ----------------------------------------------------------
# The split build emits stylesheets that *nothing in the bundle references*: no emitted JS file
# names a `.css` specifier at all, so CSS arrives only if the bootstrap document asks for it. Two
# of the three carry content-hashed names, which a hand-written link would spell right today and
# wrong at the next Monaco bump — silently, since a missing language-mode stylesheet only makes
# the editor look slightly off. So the list is generated here, from what bun actually emitted:
#
#   styles.json  the manifest, sorted, one name per line. Machine-readable; the EditorCore tests
#                compare it against a listing of this directory, so a fourth stylesheet at a
#                future Monaco version fails a test instead of going unnoticed.
#   styles.css   the same list as `@import` rules. This is what index.html links, because a
#                stylesheet is the one loader correct under all three of the view's routes: an
#                `@import` resolves against the importing sheet's own URL, so it follows the
#                document wherever it was loaded from, while `fetch()` of a sibling `file:` URL
#                is refused outright under the file-URL route.
#
# Sorted with LC_ALL=C so a rebuild of unchanged inputs stays byte-identical, which is the same
# property VERSION's missing build date protects.

stylesheets=()
while IFS= read -r stylesheet; do
    [ -n "$stylesheet" ] && stylesheets+=("$stylesheet")
done < <(cd "$resource_dir" && find . -maxdepth 1 -type f -name '*.css' | sed 's|^\./||' | LC_ALL=C sort)

{
    printf '[\n'
    index=0
    for stylesheet in "${stylesheets[@]}"; do
        index=$((index + 1))
        if [ "$index" -lt "${#stylesheets[@]}" ]; then
            printf '  "%s",\n' "$stylesheet"
        else
            printf '  "%s"\n' "$stylesheet"
        fi
    done
    printf ']\n'
} > "$resource_dir/styles.json"

{
    printf '/* Generated by Tools/build-monaco.sh from the stylesheets bun emitted; styles.json\n'
    printf '   names the same list. Do not edit; re-run the script. */\n'
    for stylesheet in "${stylesheets[@]}"; do
        printf '@import "%s";\n' "$stylesheet"
    done
} > "$resource_dir/styles.css"

file_count="$(find "$resource_dir" -type f | wc -l | tr -d ' ')"
byte_count="$(find "$resource_dir" -type f -exec cat {} + | wc -c | tr -d ' ')"

echo
echo "Monaco bundle written to Workbench/Sources/EditorCore/Resources/monaco"
echo "  monaco-editor $monaco_version, bun $bun_version"
echo "  $file_count files, $byte_count bytes"
echo "  ${#stylesheets[@]} stylesheets, named in styles.json and imported by styles.css"
